# Generated by Django 4.1.7 on 2023-03-29 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0002_alter_item_supplier_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='supplier_contact_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
